name: Build and Deploy React Project

on:
  push:
    branches:
      - v2 # Trigger on pushes to the v2 branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the current repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: v2 # Checkout the specific v2 branch

      # Set up Node.js for building the React app
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Use appropriate Node.js version for your project

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          corepack enable
          yarn install
          yarn run build  # Build command for React (adjust if different)

      # Checkout the target repository to push the build
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: Open-SL/zedv2 # Specify target repository
          token: ${{ secrets.Z_ACCESS_TOKEN }} # Use a personal access token with repo permissions
          ref: main # Target branch
          path: target-repo

      # Copy the build output to the target repo directory
      - name: Copy build output
        run: |
          # rm -rf target-repo/*
          cp -r dist/* target-repo/  # Assumes your build output is in the 'build' directory

      # Commit and push changes to the target repository
      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy React app from v2 branch"
          git push origin main
